spring:
  application:
    name: cost-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/finops}
    username: ${SPRING_DATASOURCE_USERNAME:finops}
    password: ${SPRING_DATASOURCE_PASSWORD:finops123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080

logging:
  level:
    com.finops: DEBUG
